site_name: Complex Valued Neural Networks in pytorch
site_url: "https://jeremyfix.github.io/torchcvnn/"
repo_url: "https://github.com/jeremyfix/torchcvnn"

markdown_extensions:
    - attr_list
    - admonition
    - toc:
        permalink: True
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
    - include-markdown
    - gen-files:
        scripts:
          - docs/gen_ref_pages.py
    - literate-nav:
        nav_file: SUMMARY.md
    - mkdocstrings:
        handlers:
          python:
            import:
            - https://docs.python.org/3/objects.inv
            - https://installer.readthedocs.io/en/stable/objects.inv  # demonstration purpose in the docs
            - https://mkdocstrings.github.io/autorefs/objects.inv
            paths: [src, examples]
            options:
              docstring_options:
                ignore_init_summary: true
              docstring_section_style: list
              heading_level: 1
              inherited_members: true
              merge_init_into_class: true
              separate_signature: true
              show_root_heading: false
              show_root_full_path: true
              show_signature_annotations: true
              show_symbol_type_heading: true
              show_symbol_type_toc: true
              signature_crossrefs: true
              summary: true

theme:
    name: material
    features:
      - navigation.tabs
      - toc.integrate
    icon:
      repo: fontawesome/brands/github

nav: 
  - Home: index.md
  - Installation: installation.md
  - Code reference: reference/
