site_name: Complex Valued Neural Networks in pytorch
theme: readthedocs

markdown_extensions:
    - attr_list
    - toc:
        permalink: True
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
    - include-markdown
    - mkdocstrings:
        default_handler: python

theme:
    name: readthedocs

nav: 
  - Home: index.md
  - Installation: installation.md
  - Modules:
    - torchcvnn.nn: nn.md
