name: sphinx

on:
  push:
    branches:
      - doc_refactor # To be changed to main once released
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ">= 3.8 < 3.12"

      - name: Install torchcvnn and its doc dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[docs]

      - name: Build HTML
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: sphinx_doc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: $SHINX_DOC_DIR/_build/html/

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: sphinx_doc/_build/html
