name: sphinx

on:
  push:
    branches:
      - main

jobs:

  codecov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache python modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-py310-test-${{ hashFiles('pyproject.toml') }}-docs

      - name: Install torchcvnn and its test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install -r tests/requirements.txt

      - name: Run pytest tests
        run: cd tests && pytest --doctest-modules --cov=torchcvnn --cov-report=html

      - name: Upload the codecov html report assets
        uses: actions/upload-artifact@v4
        with:
          path: tests/htmlcov
          name: htmlcov

  deploy:
    runs-on: ubuntu-latest
    needs: [codecov]

    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache python modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-py310-${{ hashFiles('pyproject.toml') }}-docs

      - name: Install torchcvnn and its doc dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[docs]

      - name: Build HTML
        run : |
          cd docs && make html

      - name: Download the code coverage report
        uses: actions/download-artifact@v4
        with:
          name: htmlcov
          path: docs/_build/html/htmlcov

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
