name: sphinx

on:
  push:
    branches:
      - doc_refactor # To be changed to main once released
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.10"]      

    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Cache python modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('pyproject.toml') }}-docs

      - name: Install torchcvnn and its doc dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[docs]

      - name: Build HTML
        run : |
          cd sphinx_doc && make html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: $SHINX_DOC_DIR/_build/html/

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: sphinx_doc/_build/html
